#fxl_game:
#    resource: "@FXLGameBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#fxl_qcm:
#    resource: "@FXLQCMBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#
#fxl_photo:
#    resource: "@FXLPhotoBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#fxl_literacy:
#    resource: "@FXLLiteracyBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#fxl_music:
#    resource: "@FXLMusicBundle/Controller/"
#    type:     annotation
#    prefix:   /

fxl_user:
    resource: "@FXLUserBundle/Controller/"
    type:     annotation
    prefix:   /

fxl_resume:
    resource: "@FXLResumeBundle/Controller/"
    type:     annotation
    prefix:   /

fxl_magic:
    resource: "@FXLMagicBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
