<?php

namespace FXL\Bundle\QCMBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmRepository extends EntityRepository
{
}
