<?php

namespace FXL\Bundle\QCMBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FXL\Component\Doctrine\Functions\MysqlRand;
/**
 * Review Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    public function findOneWithRandomQuestion($slug){
        die();
        $result = $this->createQueryBuilder('r')
             ->where("r.slug = :slug")
             ->setParameter('slug', $slug)
             ->innerJoin("r.questions", "rq")
             ->innerJoin("rq.answers", "answers")
             ->orderBy("RAND")
             ->getQuery()
             ->getSQL();

        \Doctrine\Common\Util\Debug::dump($result);
        die();
    }
}
