<?php

namespace FXL\Bundle\LiteracyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

    public function findLastGroups($groupBy=true){

        $query = $this->createQueryBuilder("g")
            ->select("g, gn, gs")
            ->where("g.published = :published")
            ->setParameter("published", true)
            ->orderBy("g.updatedAt", "desc")

            ->innerJoin("g.node", "gn")
            ->innerJoin("g.sheets", "gs")

            ->leftJoin("g.sons", "gg")
            ;

        if($groupBy){
            $query->groupBy("gs");
        }
        return $query
            ->getQuery()
            ->getResult();
    }

}
