<?php

namespace FXL\Bundle\LiteracyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetRepository extends EntityRepository
{

    public function findSheetsOrdered($groupId){
        return $this->createQueryBuilder("gs")
            ->select("gs")
            ->where("g.id = :groupId")
            ->setParameter("groupId", $groupId)
            ->innerJoin("gs.group", "g")
            ->orderBy("gs.position", "asc")
            ->getQuery()
            ->getResult();
    }
}
