<?php

namespace FXL\Bundle\LiteracyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WikipediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WikipediaRepository extends EntityRepository
{
}
